# Generated by Django 3.1.2 on 2020-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commint',
            name='body',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
