# Generated by Django 3.1.2 on 2020-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_commint_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commint',
            name='body',
            field=models.CharField(max_length=300),
        ),
    ]
