# Generated by Django 3.1.2 on 2020-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avater.jpg', upload_to='avatar/'),
        ),
    ]
