# Generated by Django 3.1.2 on 2020-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media_root/avater.jpg', upload_to='avatar/'),
        ),
    ]
